version: '3.8'

services:
  ocserv:
    build: .
    container_name: ocserv
    ports:
      - "43443:443/tcp"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      ./ocserv/cert/:/etc/ocserv/cert
    environment:
      - PUID=1027 # Change me use id $user for check
      - PGID=100 # Change me use id $user for check
      - TZ=Europe/Moscow
      - SRV_CN=vpn.example.com
      - SRV_CA=VPN
      - VPN_SUBNET=10.10.10.0/24
    restart: unless-stopped
