version: '3.8'

services:
  ocserv:
    build: .
    container_name: ocserv
    ports:
      - "43443:443/tcp"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      # - ./config/ocserv.conf:/etc/ocserv/ocserv.conf #ocserv config
      # - ./cert:/etc/ocserv/cert #folder with certificate
    environment:
      - TZ=Europe/Moscow
      - SRV_CN=vpn.example.com
      - SRV_CA=OCSERV
    restart: unless-stopped
