version: '3.8'

services:
  ocserv:
    build: .
    container_name: ocserv
    ports:
      - "443:443"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config:/etc/ocserv
    environment:
      - TZ=Europe/Moscow
      - SRV_CN=vpn.example.com
      - SRV_CA=MyVPN CA
    restart: unless-stopped
